### ISSUE TITLE
Crash in QGnomePlatformDecoration::updateButtonHoverState(Button)

### ISSUE THREAD

**Issue by chsterz** [FedoraQt/QGnomePlatform#153]
Hi, 

for my Qt 6.6.0 on Arch Linux
for a simple Qml Rotating Rect
I experience crashes at 

```
#0  0x00007ffa041b3c31 in QGnomePlatformDecoration::forceRepaint() () at /usr/lib/qt6/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so
#1  0x00007ffa041b40a8 in QGnomePlatformDecoration::updateButtonHoverState(Button) () at /usr/lib/qt6/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so
#2  0x00007ffa041b42f0 in QGnomePlatformDecoration::processMouseTop(QtWaylandClient::QWaylandInputDevice*, QPointF const&, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) () at /usr/lib/qt6/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so
#3  0x00007ffa041b47f9 in QGnomePlatformDecoration::handleMouse(QtWaylandClient::QWaylandInputDevice*, QPointF const&, QPointF const&, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) () at /usr/lib/qt6/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so
#4  0x00007ffa0d7eb365 in QtWaylandClient::QWaylandWindow::handleMouseEventWithDecoration(QtWaylandClient::QWaylandInputDevice*, QtWaylandClient::QWaylandPointerEvent const&) () at /usr/lib/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
#5  0x00007ffa0d7eb7a5 in QtWaylandClient::QWaylandWindow::handleMouse(QtWaylandClient::QWaylandInputDevice*, QtWaylandClient::QWaylandPointerEvent const&) ()
    at /usr/lib/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
#6  0x00007ffa0d7d1617 in QtWaylandClient::QWaylandInputDevice::Pointer::flushFrameEvent() () at /usr/lib/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
#7  0x00007ffa0fecf4f6 in  () at /usr/lib/libffi.so.8
#8  0x00007ffa0fecbf5e in  () at /usr/lib/libffi.so.8
#9  0x00007ffa0feceb73 in ffi_call () at /usr/lib/libffi.so.8
#10 0x00007ffa13a0f645 in  () at /usr/lib/qt6/plugins/platforms/../../../libwayland-client.so.0
#11 0x00007ffa13a0fe73 in  () at /usr/lib/qt6/plugins/platforms/../../../libwayland-client.so.0
#12 0x00007ffa13a1013c in wl_display_dispatch_queue_pending () at /usr/lib/qt6/plugins/platforms/../../../libwayland-client.so.0
#13 0x00007ffa0d7bd71e in  () at /usr/lib/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x00007ffa11da5077 in QObject::event(QEvent*) () at /usr/lib/libQt6Core.so.6
#15 0x00007ffa11d626d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#16 0x00007ffa11d62a5b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt6Core.so.6
```

my env contains 
```
QT_QPA_PLATFORMTHEME=gnome
QT_STYLE_OVERRIDE=adwaita
``` 
if that is relevant

**Comment by grulja** [comment]
It needs a rebuild after a Qt update.
